spring:
  mvc:
    view:
      suffix: .html
  profiles:
    include: >
      db
  resources:
    chain:
      strategy:
        content:
          enabled: true
server:
  port: 9000
  compression:
    enabled: true
    mime-types: text/html, text/css, text/javascript, application/javascript, application/json, image/png
    min-response-size: 2048

---
spring.profiles: set1

server:
  port: 8081
---
spring.profiles: set2

server:
  port: 8082
